/* Generated by Yosys 0.51 (git sha1 c4b5190229616f7ebf8197f43990b4429de3e420, g++ 14.3.0 -fPIC -O3) */

module single_cas(data_i, data_o);
  wire [3:0] a;
  wire [3:0] b;
  input [7:0] data_i;
  wire [7:0] data_i;
  output [7:0] data_o;
  wire [7:0] data_o;
  wire [3:0] hi;
  wire [3:0] lo;
  wire lo_LUT3_F_I2;
  wire lo_LUT3_F_I2_ALU_COUT_CIN;
  wire lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN;
  wire lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN;
  wire lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN;
  wire lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_SUM;
  wire lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_SUM;
  wire lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_SUM;
  wire lo_LUT3_F_I2_ALU_COUT_I3;
  wire lo_LUT3_F_I2_ALU_COUT_SUM;
  IBUF a_IBUF_O (
    .I(data_i[3]),
    .O(a[3])
  );
  IBUF a_IBUF_O_1 (
    .I(data_i[2]),
    .O(a[2])
  );
  IBUF a_IBUF_O_2 (
    .I(data_i[1]),
    .O(a[1])
  );
  IBUF a_IBUF_O_3 (
    .I(data_i[0]),
    .O(a[0])
  );
  IBUF b_IBUF_O (
    .I(data_i[7]),
    .O(b[3])
  );
  IBUF b_IBUF_O_1 (
    .I(data_i[6]),
    .O(b[2])
  );
  IBUF b_IBUF_O_2 (
    .I(data_i[5]),
    .O(b[1])
  );
  IBUF b_IBUF_O_3 (
    .I(data_i[4]),
    .O(b[0])
  );
  OBUF data_o_OBUF_O (
    .I(hi[3]),
    .O(data_o[7])
  );
  OBUF data_o_OBUF_O_1 (
    .I(hi[2]),
    .O(data_o[6])
  );
  OBUF data_o_OBUF_O_2 (
    .I(hi[1]),
    .O(data_o[5])
  );
  OBUF data_o_OBUF_O_3 (
    .I(hi[0]),
    .O(data_o[4])
  );
  OBUF data_o_OBUF_O_4 (
    .I(lo[3]),
    .O(data_o[3])
  );
  OBUF data_o_OBUF_O_5 (
    .I(lo[2]),
    .O(data_o[2])
  );
  OBUF data_o_OBUF_O_6 (
    .I(lo[1]),
    .O(data_o[1])
  );
  OBUF data_o_OBUF_O_7 (
    .I(lo[0]),
    .O(data_o[0])
  );
  LUT2 #(
    .INIT(4'he)
  ) hi_LUT2_F (
    .F(hi[3]),
    .I0(a[3]),
    .I1(b[3])
  );
  LUT3 #(
    .INIT(8'hac)
  ) hi_LUT3_F (
    .F(hi[1]),
    .I0(a[1]),
    .I1(b[1]),
    .I2(lo_LUT3_F_I2)
  );
  LUT3 #(
    .INIT(8'hac)
  ) hi_LUT3_F_1 (
    .F(hi[2]),
    .I0(a[2]),
    .I1(b[2]),
    .I2(lo_LUT3_F_I2)
  );
  LUT3 #(
    .INIT(8'hac)
  ) hi_LUT3_F_2 (
    .F(hi[0]),
    .I0(a[0]),
    .I1(b[0]),
    .I2(lo_LUT3_F_I2)
  );
  LUT2 #(
    .INIT(4'h8)
  ) lo_LUT2_F (
    .F(lo[3]),
    .I0(a[3]),
    .I1(b[3])
  );
  LUT3 #(
    .INIT(8'hca)
  ) lo_LUT3_F (
    .F(lo[1]),
    .I0(a[1]),
    .I1(b[1]),
    .I2(lo_LUT3_F_I2)
  );
  LUT3 #(
    .INIT(8'hca)
  ) lo_LUT3_F_1 (
    .F(lo[2]),
    .I0(a[2]),
    .I1(b[2]),
    .I2(lo_LUT3_F_I2)
  );
  LUT3 #(
    .INIT(8'hca)
  ) lo_LUT3_F_2 (
    .F(lo[0]),
    .I0(a[0]),
    .I1(b[0]),
    .I2(lo_LUT3_F_I2)
  );
  ALU #(
    .ALU_MODE(32'sd2)
  ) lo_LUT3_F_I2_ALU_COUT (
    .CIN(lo_LUT3_F_I2_ALU_COUT_CIN),
    .COUT(lo_LUT3_F_I2),
    .I0(a[3]),
    .I1(b[3]),
    .I3(lo_LUT3_F_I2_ALU_COUT_I3),
    .SUM(lo_LUT3_F_I2_ALU_COUT_SUM)
  );
  ALU #(
    .ALU_MODE(32'sd2)
  ) lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT (
    .CIN(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN),
    .COUT(lo_LUT3_F_I2_ALU_COUT_CIN),
    .I0(a[2]),
    .I1(b[2]),
    .I3(lo_LUT3_F_I2_ALU_COUT_I3),
    .SUM(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_SUM)
  );
  ALU #(
    .ALU_MODE(32'sd2)
  ) lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT (
    .CIN(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN),
    .COUT(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN),
    .I0(a[1]),
    .I1(b[1]),
    .I3(lo_LUT3_F_I2_ALU_COUT_I3),
    .SUM(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_SUM)
  );
  ALU #(
    .ALU_MODE(32'sd2)
  ) lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT (
    .CIN(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN),
    .COUT(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN),
    .I0(a[0]),
    .I1(b[0]),
    .I3(lo_LUT3_F_I2_ALU_COUT_I3),
    .SUM(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_SUM)
  );
  VCC lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_VCC_V (
    .V(lo_LUT3_F_I2_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN_ALU_COUT_CIN)
  );
  GND lo_LUT3_F_I2_ALU_COUT_I3_GND_G (
    .G(lo_LUT3_F_I2_ALU_COUT_I3)
  );
endmodule
