/* Generated by Yosys 0.51 (git sha1 c4b5190229616f7ebf8197f43990b4429de3e420, g++ 14.3.0 -fPIC -O3) */

module single_cas(data_i, data_o);
  wire a;
  wire b;
  input [1:0] data_i;
  wire [1:0] data_i;
  output [1:0] data_o;
  wire [1:0] data_o;
  wire hi;
  wire lo;
  assign lo = 4'h8 >> { data_i[0], data_i[1] };
  assign hi = 4'he >> { data_i[0], data_i[1] };
  assign a = data_i[0];
  assign b = data_i[1];
  assign data_o = { hi, lo };
endmodule
