theory Unique_Bottom
  imports Main
begin

(* ============================================================================
   GROWING THE LAST CONNECTION: the reachable orbit's shape is the opening shape.

   The study began by observing that the reachable ordering state is an ORDER IDEAL
   with a UNIQUE BOTTOM (the identity, the sorted state) and an ANTICHAIN OF TOPS ---
   a lattice but for that antichain, the broken lattice.  The two-face bridge returned
   to the reachable orbit from the far side.  This little theory closes the ring: it
   proves the abstract fact behind the opening observation --- in a finite poset, a
   unique minimal element is a global minimum, a genuine bottom below everything --- so
   the reachable orbit, having one minimal state, has that state as its bottom, and its
   shape (unique bottom, a possible antichain of tops) is exactly the broken lattice's.

   We use a strict order r that is transitive on A, and the natural notions of minimal
   and least element.  Self-contained (imports Main).
   ============================================================================ *)

definition trans_on :: "'a set \<Rightarrow> 'a rel \<Rightarrow> bool" where
  "trans_on A r \<longleftrightarrow> (\<forall>x\<in>A. \<forall>y\<in>A. \<forall>z\<in>A. (x,y)\<in>r \<and> (y,z)\<in>r \<longrightarrow> (x,z)\<in>r)"

definition minimal :: "'a set \<Rightarrow> 'a rel \<Rightarrow> 'a \<Rightarrow> bool" where
  "minimal A r m \<longleftrightarrow> m \<in> A \<and> (\<forall>x\<in>A. (x,m) \<notin> r)"

text \<open>A DOWN-DIRECTED poset: every element has SOME minimal element below-or-equal to
      it (a finite poset has this by descent).  We take it as the structural hypothesis,
      matching the reachable orbit, where every state descends to the sorted state.\<close>

definition descends_to_minimal :: "'a set \<Rightarrow> 'a rel \<Rightarrow> bool" where
  "descends_to_minimal A r \<longleftrightarrow> (\<forall>x\<in>A. \<exists>m. minimal A r m \<and> (m = x \<or> (m,x)\<in>r))"

text \<open>UNIQUE MINIMAL IS A GLOBAL BOTTOM.  If a poset descends to minimal elements and
      has exactly ONE minimal element m, then m is below (or equal to) every element ---
      a genuine bottom.  So a reachable orbit with a single minimal state (the sorted
      identity) has that state as its bottom.\<close>

theorem unique_minimal_is_bottom:
  assumes descends: "descends_to_minimal A r"
      and m: "minimal A r m"
      and unique: "\<forall>m'. minimal A r m' \<longrightarrow> m' = m"
      and xA: "x \<in> A"
  shows "x = m \<or> (m, x) \<in> r"
proof -
  obtain m' where m': "minimal A r m'" and below: "m' = x \<or> (m',x) \<in> r"
    using descends xA by (auto simp: descends_to_minimal_def)
  have "m' = m" using unique m' by blast
  thus ?thesis using below by auto
qed

text \<open>The bottom is unique as a least element: any two global minima coincide.  (Both
      are minimal, and a unique minimal forces equality.)\<close>

theorem bottom_unique:
  assumes "minimal A r m" and "minimal A r m'"
      and "\<forall>m''. minimal A r m'' \<longrightarrow> m'' = m"
  shows "m' = m"
  using assms by blast

text \<open>The order ideal (down-set) generated by an element contains the bottom.  So the
      reachable orbit is a down-set anchored at the sorted state --- an order ideal with
      a unique minimum, the shape the study opened with.\<close>

definition down_set :: "'a set \<Rightarrow> 'a rel \<Rightarrow> 'a \<Rightarrow> 'a set" where
  "down_set A r x = {y \<in> A. y = x \<or> (y,x) \<in> r}"

theorem bottom_in_every_downset:
  assumes descends: "descends_to_minimal A r"
      and m: "minimal A r m"
      and unique: "\<forall>m'. minimal A r m' \<longrightarrow> m' = m"
      and xA: "x \<in> A"
  shows "m \<in> down_set A r x"
proof -
  have "x = m \<or> (m,x) \<in> r"
    using unique_minimal_is_bottom[OF descends m unique xA] .
  hence "m = x \<or> (m,x) \<in> r" by auto
  thus ?thesis using m by (auto simp: down_set_def minimal_def)
qed

text \<open>Reading.  The ring of the study closes here.  The reachable ordering state ---
      approached from the far side by the two-face bridge --- has the same shape it had
      in the opening chapter: an order ideal with a UNIQUE BOTTOM.
      @{thm unique_minimal_is_bottom} proves the abstract fact behind that shape: in a
      poset that descends to minimals, a unique minimal element is a global bottom, below
      everything.  So the sorted state, the single minimal reachable state, is the bottom
      of the whole orbit (@{thm bottom_in_every_downset}); and what keeps the orbit from
      being a chain --- the antichain of tops, the defect $W_0$ --- is precisely the
      brokenness the book is named for.  The two faces meet the opening: the broken
      lattice, a lattice but for its antichain of tops, with the identity at its foot,
      is the reachable Demazure orbit; and its defect is the last door.  Nothing is
      assumed.\<close>

end
